In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import GroupKFold
from sklearn.tree     import DecisionTreeClassifier

In [3]:
frame_data = pd.read_csv('FPS_DATA.CSV')

frame_data.head()

,"SPEC(High, Mid, Low)",CPU NAME,CPU BenchMark,CPU Core,CPU Thread,CPU ClockSpeed GHZ,CPU ClockSpeed Turbo GHz,GPU NAME,GPU BenchMark,GPU Memory GB,GPU Clock MHz,GPU Clock Boost MHz,GAME NAME,RESOLUTION,GAME SETTING,GAME MIN FRAME,GAME AVG FRAME,GAME MAX FRAME
0,High,Intel Core i9-12900,38803.0,16.0,24.0,2.4,5.1,GeForce RTX 3090,26303.0,24.0,1560.0,1860.0,1,QHD,ULTRA,71.0,87,133.0
1,High,Intel Core i9-12900,38803.0,16.0,24.0,2.4,5.1,GeForce RTX 3090,26303.0,24.0,1560.0,1860.0,1,QHD,HIGH,96.0,117,179.0
2,High,Intel Core i9-12900,38803.0,16.0,24.0,2.4,5.1,GeForce RTX 3090,26303.0,24.0,1560.0,1860.0,1,QHD,MEDIUM,125.0,152,234.0
3,High,Intel Core i9-12900,38803.0,16.0,24.0,2.4,5.1,GeForce RTX 3080 Ti,26619.0,12.0,1365.0,1665.0,1,QHD,ULTRA,65.0,80,122.0
4,High,Intel Core i9-12900,38803.0,16.0,24.0,2.4,5.1,GeForce RTX 3080 Ti,26619.0,12.0,1365.0,1665.0,1,QHD,HIGH,88.0,108,162.0

In [4]:
frame_Y = pd.DataFrame(frame_data['GAME AVG FRAME'], columns = ['GAME AVG FRAME'])
frame_Y[:5]

   GAME AVG FRAME
0              87
1             117
2             152
3              80
4             108

In [5]:
scale_cols = ['CPU BenchMark', 'GPU BenchMark', 'CPU Core', 'CPU Thread', 'GPU Memory GB', 'GPU Clock Boost MHz', 'GAME NAME']
data_temp  = frame_data[scale_cols]
frame_X = pd.DataFrame(data_temp)

frame_X[:5]

,CPU BenchMark,GPU BenchMark,CPU Core,CPU Thread,GPU Memory GB,GPU Clock Boost MHz,GAME NAME
0,38803.0,26303.0,16.0,24.0,24.0,1860.0,1
1,38803.0,26303.0,16.0,24.0,24.0,1860.0,1
2,38803.0,26303.0,16.0,24.0,24.0,1860.0,1
3,38803.0,26619.0,16.0,24.0,12.0,1665.0,1
4,38803.0,26619.0,16.0,24.0,12.0,1665.0,1

In [6]:
groups = pd.DataFrame(frame_data['GAME NAME'])

groups[:3]

   GAME NAME
0          1
1          1
2          1

In [7]:
# 모델 선언
fold_df_clf = DecisionTreeClassifier()

# Kfold
SPLITS = 5
kf = KFold(n_splits = SPLITS)
n_iter = 0

In [8]:
label  = pd.DataFrame(frame_data['GAME NAME'])

features = frame_data

df_specs = pd.DataFrame(data=None, columns=frame_data.columns, index=frame_data.index)
df_specs.dropna()

Empty DataFrame
Columns: [SPEC(High, Mid, Low), CPU NAME, CPU BenchMark, CPU Core, CPU Thread, CPU ClockSpeed GHZ, CPU ClockSpeed Turbo GHz, GPU NAME, GPU BenchMark, GPU Memory GB, GPU Clock MHz, GPU Clock Boost MHz, GAME NAME, RESOLUTION, GAME SETTING, GAME MIN FRAME, GAME AVG FRAME, GAME MAX FRAME]
Index: []

In [10]:
fold = 1
for train_index, validate_index  in kf.split(frame_data):
    trainDF = pd.DataFrame(frame_data.iloc[train_index])
    validateDF = pd.DataFrame(frame_data.iloc[validate_index])
    trainDF[['set', 'iteration']] = 'T', fold
    validateDF[['set', 'iteration']] = 'V', fold
    print("Fold #{}, Training Size: {}, Validation Size: {}".format(fold,len(trainDF),len(validateDF)))
    fold+=1
    df_specs = pd.concat([df_specs, validateDF,trainDF])

df_specs.to_csv("./auto-mpg-kfold5.csv")
print(df_specs)

Fold #1, Training Size: 266, Validation Size: 67
Fold #2, Training Size: 266, Validation Size: 67
Fold #3, Training Size: 266, Validation Size: 67
Fold #4, Training Size: 267, Validation Size: 66
Fold #5, Training Size: 267, Validation Size: 66
    SPEC(High, Mid, Low)              CPU NAME  CPU BenchMark  CPU Core  \
0                    NaN                   NaN            NaN       NaN
1                    NaN                   NaN            NaN       NaN
2                    NaN                   NaN            NaN       NaN
3                    NaN                   NaN            NaN       NaN
4                    NaN                   NaN            NaN       NaN
..                   ...                   ...            ...       ...
262                 High  Intel Core i5-12600K        27341.0      10.0
263                 High  Intel Core i5-12600K        27341.0      10.0
264                 High  Intel Core i5-12600K        27341.0      10.0
265                 High  Intel Core i5-12600K        27341.0      10.0
266                 High  Intel Core i5-12600K        27341.0      10.0

     CPU Thread  CPU ClockSpeed GHZ  CPU ClockSpeed Turbo GHz  \
0           NaN                 NaN                       NaN
1           NaN                 NaN                       NaN
2           NaN                 NaN                       NaN
3           NaN                 NaN                       NaN
4           NaN                 NaN                       NaN
..          ...                 ...                       ...
262        16.0                 3.7                       4.9
263        16.0                 3.7                       4.9
264        16.0                 3.7                       4.9
265        16.0                 3.7                       4.9
266        16.0                 3.7                       4.9

                GPU NAME  GPU BenchMark  GPU Memory GB  GPU Clock MHz  \
0                    NaN            NaN            NaN            NaN
1                    NaN            NaN            NaN            NaN
2                    NaN            NaN            NaN            NaN
3                    NaN            NaN            NaN            NaN
4                    NaN            NaN            NaN            NaN
..                   ...            ...            ...            ...
262  GeForce RTX 3070 Ti        23166.0            8.0         1575.0
263  GeForce RTX 3070 Ti        23166.0            8.0         1575.0
264   AMD Radeon RX 6800        20660.0           16.0         1700.0
265   AMD Radeon RX 6800        20660.0           16.0         1700.0
266   AMD Radeon RX 6800        20660.0           16.0         1700.0

     GPU Clock Boost MHz GAME NAME RESOLUTION GAME SETTING  GAME MIN FRAME  \
0                    NaN       NaN        NaN          NaN             NaN
1                    NaN       NaN        NaN          NaN             NaN
2                    NaN       NaN        NaN          NaN             NaN
3                    NaN       NaN        NaN          NaN             NaN
4                    NaN       NaN        NaN          NaN             NaN
..                   ...       ...        ...          ...             ...
262               1770.0         3        QHD         HIGH           404.0
263               1770.0         3        QHD       MEDIUM           528.0
264               1815.0         3        QHD        ULTRA           300.0
265               1815.0         3        QHD         HIGH           404.0
266               1815.0         3        QHD       MEDIUM           528.0

    GAME AVG FRAME  GAME MAX FRAME  set  iteration
0              NaN             NaN  NaN        NaN
1              NaN             NaN  NaN        NaN
2              NaN             NaN  NaN        NaN
3              NaN             NaN  NaN        NaN
4              NaN             NaN  NaN        NaN
..             ...             ...  ...        ...
262            540           804.0    T        5.0
263            705          1040.0    T        5.0
264            400           596.0    T        5.0
265            540           804.0    T        5.0
266            705          1040.0    T        5.0

[3663 rows x 20 columns]